"use client";
import {FormEvent,useEffect,useState} from "react";
import {CircleDollarSign,RotateCcw} from "lucide-react";
import {supabase} from "@/lib/supabase";
type Book={id:string;starts_at:string;subtotal_cents:number;security_deposit_cents?:number;cleaning_fee_cents?:number};
type Invoice={id:string;invoice_number:string;booking_id:string;amount_due_cents:number;deposit_due_cents:number;amount_paid_cents:number;status:string;balance_due_at:string|null};
type Refund={id:string;booking_id:string;amount_cents:number;reason:string;status:string;admin_note:string|null;created_at:string};
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);
export default function BillingOperations({bookings,label,onNotice,onRefresh}:{bookings:Book[];label:(id:string)=>string;onNotice:(s:string)=>void;onRefresh:()=>Promise<void>}){
 const [invoices,setInvoices]=useState<Invoice[]>([]),[refunds,setRefunds]=useState<Refund[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{const [i,r]=await Promise.all([supabase.from("booking_invoices").select("id,invoice_number,booking_id,amount_due_cents,deposit_due_cents,amount_paid_cents,status,balance_due_at").order("created_at",{ascending:false}),supabase.from("refund_requests").select("id,booking_id,amount_cents,reason,status,admin_note,created_at").order("created_at",{ascending:false})]);if(i.error||r.error)onNotice(i.error?.message||r.error!.message);else{setInvoices((i.data||[]) as Invoice[]);setRefunds((r.data||[]) as Refund[])}};
 useEffect(()=>{load()},[]);
 const payment=async(e:FormEvent<HTMLFormElement>,id:string)=>{e.preventDefault();setBusy(true);const v=Object.fromEntries(new FormData(e.currentTarget).entries());const {error}=await supabase.rpc("admin_record_booking_payment",{p_invoice_id:id,p_amount_cents:Math.round(Number(v.amount)*100),p_transaction_type:v.transaction_type,p_payment_provider:v.payment_provider,p_external_reference:v.reference||null,p_notes:v.notes||null});if(error)onNotice(error.message);else{onNotice("Payment recorded and invoice updated.");e.currentTarget.reset();await Promise.all([load(),onRefresh()])}setBusy(false)};
 const decide=async(form:HTMLFormElement,id:string,decision:string)=>{setBusy(true);const v=Object.fromEntries(new FormData(form).entries());const {error}=await supabase.rpc("admin_decide_refund_request",{p_request_id:id,p_decision:decision,p_admin_note:v.admin_note||null});if(error)onNotice(error.message);else{onNotice(`Refund ${decision}. Processing must be recorded after funds are returned.`);await load()}setBusy(false)};
 return <><section className="ops-panel"><header><CircleDollarSign/><h2>Provider-issued invoices</h2></header>{invoices.length?<div className="invoice-admin-list">{invoices.map(i=><form key={i.id} onSubmit={e=>payment(e,i.id)}><header><div><b>{i.invoice_number}</b><span>{label(i.booking_id)}</span></div><em>{i.status}</em></header><p>{money(i.amount_paid_cents)} paid of {money(i.amount_due_cents)} • {money(Math.max(0,i.amount_due_cents-i.amount_paid_cents))} due</p>{i.status!=="paid"&&i.status!=="void"&&<><div className="form-pair"><label>Payment received<input name="amount" type="number" min=".01" step=".01" required/></label><label>Type<select name="transaction_type"><option value="deposit">Deposit</option><option value="balance">Balance</option><option value="rent_charge">Rent charge</option><option value="adjustment">Adjustment</option></select></label></div><div className="form-pair"><label>Received via<select name="payment_provider"><option value="manual">Manual entry</option><option value="cash">Cash</option><option value="other">Other</option></select></label><label>Reference<input name="reference" placeholder="Receipt or check number"/></label></div><button className="primary" disabled={busy}>Record processed payment</button></>}</form>)}</div>:<p>No kitchen-issued invoices yet.</p>}</section><section className="ops-panel refund-queue"><header><RotateCcw/><h2>Refund oversight</h2></header>{refunds.length?<div>{refunds.map(r=><form key={r.id}><header><div><b>{money(r.amount_cents)} • {label(r.booking_id)}</b><span>{r.reason}</span></div><em>{r.status}</em></header><label>Decision / processing note<textarea name="admin_note" defaultValue={r.admin_note||""}/></label>{r.status==="pending"&&<footer><button type="button" disabled={busy} onClick={e=>decide(e.currentTarget.form!,r.id,"declined")}>Decline</button><button type="button" disabled={busy} onClick={e=>decide(e.currentTarget.form!,r.id,"approved")}>Approve</button></footer>}</form>)}</div>:<p>No refund requests.</p>}</section></>
}
