"use client";
import {FormEvent,useEffect,useState} from "react";
import {AlertTriangle,Check,Clock3,Flag,LogIn,LogOut,ShieldCheck} from "lucide-react";
import {supabase} from "@/lib/supabase";
import "./booking-access.css";
import "./incident-report.css";

const items=[["dishes_clean","Dishes and utensils washed and put away"],["surfaces_sanitized","Prep surfaces cleaned and sanitized"],["equipment_off","Ovens, fryers, griddle, and equipment turned off"],["lights_off","Lights turned off"],["waste_removed","Trash, food waste, and personal items removed"],["doors_secured","Doors, truck, and access points secured"]] as const;
type Booking={id:string;kitchen_id:string;starts_at:string;ends_at:string;status:string};

export default function BookingAccess(){
 const [booking,setBooking]=useState<Booking|null>(null),[inAt,setInAt]=useState(false),[outAt,setOutAt]=useState(false),[checks,setChecks]=useState<Record<string,boolean>>({}),[message,setMessage]=useState(""),[issue,setIssue]=useState(false),[userId,setUserId]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;setUserId(session.user.id);const {data:m}=await supabase.from("business_members").select("business_id").eq("user_id",session.user.id).eq("role","owner").maybeSingle();if(!m)return;const now=new Date(),from=new Date(now.getTime()-4*3600000).toISOString(),to=new Date(now.getTime()+2*3600000).toISOString();const {data:b}=await supabase.from("bookings").select("id,kitchen_id,starts_at,ends_at,status").eq("renter_business_id",m.business_id).eq("status","confirmed").lte("starts_at",to).gte("ends_at",from).order("starts_at").limit(1).maybeSingle();if(!b)return;setBooking(b as Booking);const {data:e}=await supabase.from("access_events").select("event_type").eq("booking_id",b.id).eq("user_id",session.user.id);setInAt(!!e?.some(x=>x.event_type==="check_in"));setOutAt(!!e?.some(x=>x.event_type==="check_out"))})()},[]);
 const record=async(type:"check_in"|"check_out")=>{if(!booking)return;setMessage("");const {error}=await supabase.rpc("record_booking_access",{p_booking_id:booking.id,p_event_type:type,p_items:type==="check_out"?checks:{},p_notes:null});if(error)setMessage(error.message);else if(type==="check_in"){setInAt(true);setMessage("Checked in. Your session is active.")}else{setOutAt(true);setMessage("Checkout complete. Your confirmations were recorded.")}};
 const report=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!booking||!userId)return;const v=Object.fromEntries(new FormData(e.currentTarget).entries());const {error}=await supabase.from("incident_reports").insert({booking_id:booking.id,kitchen_id:booking.kitchen_id,reported_by:userId,incident_type:v.incident_type,description:v.description,emergency_services_called:v.emergency_services_called==="on",occurred_at:new Date().toISOString()});if(error)setMessage(error.message);else{setIssue(false);setMessage("Issue reported. TaGo's administration and the kitchen provider can now review it.");e.currentTarget.reset()}};
 if(!booking)return <section className="access-flow empty"><Clock3/><div><b>No confirmed booking is currently in its access window</b><span>Check-in opens two hours before your reservation and remains available through closeout.</span></div></section>;
 const complete=items.every(([k])=>checks[k]);
 return <section className="access-flow"><header><div><p>REQUIRED SESSION CONTROL</p><h2>Check in & close out</h2><span>{new Date(booking.starts_at).toLocaleString()} – {new Date(booking.ends_at).toLocaleTimeString()}</span></div><span><ShieldCheck/> Time-stamped</span></header><div className="access-columns"><article className={inAt?"done":""}><b><i>{inAt?<Check/>:"1"}</i>Arrival</b><p>Check in when you enter the kitchen.</p><button disabled={inAt} onClick={()=>record("check_in")}><LogIn/>{inAt?"Checked in":"Check in"}</button><button className="issue-trigger" onClick={()=>setIssue(!issue)}><Flag/>Report an issue</button></article><article className={outAt?"done":!inAt?"locked":""}><b><i>{outAt?<Check/>:"2"}</i>Required checkout</b><p>Every item must be confirmed before leaving.</p>{items.map(([k,label])=><label key={k}><input type="checkbox" checked={!!checks[k]} disabled={!inAt||outAt} onChange={e=>setChecks(c=>({...c,[k]:e.target.checked}))}/>{label}</label>)}<button disabled={!inAt||!complete||outAt} onClick={()=>record("check_out")}><LogOut/>{outAt?"Checked out":"Complete checkout"}</button></article></div>{issue&&<form className="issue-form" onSubmit={report}><div><AlertTriangle/><span><b>Report a kitchen issue</b>This report is permanently tied to this booking.</span></div><label>Issue type<select name="incident_type" required><option>Equipment problem</option><option>Cleanliness or sanitation</option><option>Access or security</option><option>Injury or safety</option><option>Conflict with another user</option><option>Other</option></select></label><label>What happened?<textarea name="description" required minLength={10}/></label><label className="emergency-check"><input type="checkbox" name="emergency_services_called"/>Emergency services were contacted</label><button>Submit report</button></form>}{message&&<div className="access-note">{message}</div>}</section>
}
