"use client";
import {FormEvent,useEffect,useState} from "react";
import {CircleDollarSign,CreditCard,ReceiptText,RotateCcw} from "lucide-react";
import {supabase} from "@/lib/supabase";
type Invoice={id:string;invoice_number:string;booking_id:string;amount_due_cents:number;deposit_due_cents:number;amount_paid_cents:number;deposit_due_at:string|null;balance_due_at:string|null;status:string;notes:string|null};
type Refund={id:string;booking_id:string;amount_cents:number;reason:string;status:string;admin_note:string|null;created_at:string};
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);
export default function BillingCenter({bookingLabel,onNotice}:{bookingLabel:(id:string)=>string;onNotice:(s:string)=>void}){
 const [invoices,setInvoices]=useState<Invoice[]>([]),[refunds,setRefunds]=useState<Refund[]>([]),[open,setOpen]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const load=async()=>{const [i,r]=await Promise.all([supabase.from("booking_invoices").select("id,invoice_number,booking_id,amount_due_cents,deposit_due_cents,amount_paid_cents,deposit_due_at,balance_due_at,status,notes").order("created_at",{ascending:false}),supabase.from("refund_requests").select("id,booking_id,amount_cents,reason,status,admin_note,created_at").order("created_at",{ascending:false})]);if(i.error||r.error)onNotice(i.error?.message||r.error!.message);else{setInvoices((i.data||[]) as Invoice[]);setRefunds((r.data||[]) as Refund[])}};
 useEffect(()=>{load()},[]);
 const refund=async(e:FormEvent<HTMLFormElement>,invoice:Invoice)=>{e.preventDefault();setBusy(true);const v=Object.fromEntries(new FormData(e.currentTarget).entries());const {error}=await supabase.rpc("submit_refund_request",{p_booking_id:invoice.booking_id,p_amount_cents:Math.round(Number(v.amount)*100),p_reason:v.reason});if(error)onNotice(error.message);else{onNotice("Refund request sent for review.");setOpen(null);await load()}setBusy(false)};
 const pay=async(invoice:Invoice)=>{setBusy(true);const {data:{session}}=await supabase.auth.getSession();if(!session){onNotice("Sign in again to pay this invoice.");setBusy(false);return}const response=await fetch("/api/stripe/bookings/checkout",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:JSON.stringify({bookingId:invoice.booking_id})});const result=await response.json() as any;if(!response.ok||!result.url){onNotice(result.error||"Checkout is unavailable.");setBusy(false);return}location.href=result.url};
 const outstanding=invoices.reduce((s,i)=>s+Math.max(0,i.amount_due_cents-i.amount_paid_cents),0);
 return <section className="billing-center"><header><CircleDollarSign/><div><h2>Billing center</h2><span>Invoices, balances, receipts and refund requests.</span></div><b>{money(outstanding)} due</b></header>{invoices.length?<div className="invoice-list">{invoices.map(i=>{const balance=Math.max(0,i.amount_due_cents-i.amount_paid_cents),pending=refunds.some(r=>r.booking_id===i.booking_id&&r.status==="pending");return <article key={i.id}><header><div><b>{i.invoice_number}</b><span>{bookingLabel(i.booking_id)}</span></div><em className={i.status}>{i.status.replaceAll("_"," ")}</em></header><div className="invoice-amounts"><span>Total<b>{money(i.amount_due_cents)}</b></span><span>Paid<b>{money(i.amount_paid_cents)}</b></span><span>Balance<b>{money(balance)}</b></span></div>{i.deposit_due_at&&<small>Deposit {money(i.deposit_due_cents)} due {new Date(i.deposit_due_at).toLocaleDateString()}</small>}{i.balance_due_at&&<small>Final balance due {new Date(i.balance_due_at).toLocaleDateString()}</small>}{i.notes&&<p>{i.notes}</p>}{balance>0&&<button disabled={busy} onClick={()=>pay(i)}><CreditCard/>Pay securely with Stripe</button>}{i.amount_paid_cents>0&&<button disabled={pending} onClick={()=>setOpen(open===i.id?null:i.id)}><RotateCcw/>{pending?"Refund pending":"Request refund"}</button>}{open===i.id&&!pending&&<form onSubmit={e=>refund(e,i)}><label>Refund amount<input name="amount" type="number" min="0.01" max={(i.amount_paid_cents/100).toFixed(2)} step=".01" required/></label><label>Reason<textarea name="reason" minLength={5} required/></label><button disabled={busy}>Submit request</button></form>}</article>})}</div>:<div className="billing-empty"><ReceiptText/><b>No invoices yet</b><span>An invoice will appear after the kitchen approves your booking request.</span></div>}{refunds.length>0&&<div className="refund-history"><h3>Refund history</h3>{refunds.map(r=><p key={r.id}><span>{money(r.amount_cents)} • {r.reason}</span><b>{r.status}</b>{r.admin_note&&<small>{r.admin_note}</small>}</p>)}</div>}</section>
}
