"use client";
import {FormEvent,useEffect,useState} from "react";
import {CalendarClock,Check,RotateCcw,X} from "lucide-react";
import {supabase} from "@/lib/supabase";
type Booking={id:string;kitchen_id:string;starts_at:string;ends_at:string;status:string};
type Change={id:string;booking_id:string;request_type:string;requested_starts_at:string|null;requested_ends_at:string|null;reason:string;status:string;admin_note:string|null;created_at:string};
const local=(iso:string)=>new Date(new Date(iso).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
export default function BookingChanges({bookings,onNotice}:{bookings:Booking[];onNotice:(s:string)=>void}){
 const [changes,setChanges]=useState<Change[]>([]),[open,setOpen]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const load=async()=>{const {data,error}=await supabase.from("booking_change_requests").select("id,booking_id,request_type,requested_starts_at,requested_ends_at,reason,status,admin_note,created_at").order("created_at",{ascending:false});if(error)onNotice(error.message);else setChanges((data||[]) as Change[])};
 useEffect(()=>{load()},[]);
 const submit=async(e:FormEvent<HTMLFormElement>,booking:Booking)=>{e.preventDefault();setBusy(true);const v=Object.fromEntries(new FormData(e.currentTarget).entries()),type=String(v.request_type);const {error}=await supabase.rpc("submit_booking_change",{p_booking_id:booking.id,p_request_type:type,p_reason:v.reason,p_requested_starts_at:type==="reschedule"?new Date(String(v.starts_at)).toISOString():null,p_requested_ends_at:type==="reschedule"?new Date(String(v.ends_at)).toISOString():null});if(error)onNotice(error.message);else{onNotice("Booking change sent to TaGo's for review.");setOpen(null);await load()}setBusy(false)};
 const eligible=bookings.filter(b=>["pending_payment","confirmed"].includes(b.status)&&new Date(b.starts_at)>new Date());
 return <section className="booking-changes"><header><CalendarClock/><div><h2>Changes & cancellations</h2><span>Keep the kitchen, equipment and payment record coordinated.</span></div></header>{changes.length>0&&<div className="change-history">{changes.map(c=><article key={c.id}><div><b>{c.request_type}</b><span>{new Date(c.created_at).toLocaleDateString()} • {c.reason}</span>{c.requested_starts_at&&<small>Requested: {new Date(c.requested_starts_at).toLocaleString()}</small>}{c.admin_note&&<small>TaGo&apos;s: {c.admin_note}</small>}</div><em className={c.status}>{c.status}</em></article>)}</div>}{eligible.map(b=>{const pending=changes.some(c=>c.booking_id===b.id&&c.status==="pending");return <div className="change-booking" key={b.id}><div><b>{new Date(b.starts_at).toLocaleString()}</b><span>{b.status.replaceAll("_"," ")}</span></div><button disabled={pending} onClick={()=>setOpen(open===b.id?null:b.id)}>{pending?<><Check/>Pending review</>:open===b.id?<><X/>Close</>:<><RotateCcw/>Request change</>}</button>{open===b.id&&!pending&&<form onSubmit={e=>submit(e,b)}><label>Request<select name="request_type" onChange={e=>e.currentTarget.form?.classList.toggle("reschedule",e.target.value==="reschedule")}><option value="cancel">Cancel booking</option><option value="reschedule">Reschedule booking</option></select></label><div className="new-times"><label>New start<input name="starts_at" type="datetime-local" defaultValue={local(b.starts_at)}/></label><label>New end<input name="ends_at" type="datetime-local" defaultValue={local(b.ends_at)}/></label></div><label>Reason<textarea name="reason" required minLength={5} placeholder="Tell TaGo's what changed…"/></label><button disabled={busy}>Send request</button></form>}</div>})}{eligible.length===0&&changes.length===0&&<p>No future bookings are eligible for changes.</p>}</section>
}
