revoke execute on function public.is_business_member(uuid) from public, anon, authenticated;
grant execute on function public.is_business_member(uuid) to service_role;
create policy "audit events blocked from client access" on public.audit_events for select to authenticated using (false);
drop policy "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select using (id=(select auth.uid()));
drop policy "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update using (id=(select auth.uid())) with check (id=(select auth.uid()));
drop policy "members read memberships" on public.business_members;
create policy "members read memberships" on public.business_members for select using (user_id=(select auth.uid()) or public.is_business_member(business_id));
drop policy "renters create bookings" on public.bookings;
create policy "renters create bookings" on public.bookings for insert with check (created_by=(select auth.uid()) and public.is_business_member(renter_business_id));
create index audit_events_actor_idx on public.audit_events(actor_id);
create index booking_resources_group_idx on public.booking_resources(group_id);
create index booking_resources_resource_idx on public.booking_resources(resource_id);
create index bookings_created_by_idx on public.bookings(created_by);
create index business_members_user_idx on public.business_members(user_id);
create index businesses_created_by_idx on public.businesses(created_by);
create index credentials_reviewer_idx on public.credentials(reviewer_id);
create index equipment_group_members_resource_idx on public.equipment_group_members(resource_id);
create index equipment_groups_kitchen_idx on public.equipment_groups(kitchen_id);
create index equipment_resources_kitchen_idx on public.equipment_resources(kitchen_id);
create index kitchens_owner_business_idx on public.kitchens(owner_business_id);
