create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;
create or replace function private.is_business_member(target uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.business_members where business_id=target and user_id=(select auth.uid())); $$;
revoke all on function private.is_business_member(uuid) from public, anon;
grant execute on function private.is_business_member(uuid) to authenticated;
drop policy "members read businesses" on public.businesses;
create policy "members read businesses" on public.businesses for select using(private.is_business_member(id));
drop policy "members read memberships" on public.business_members;
create policy "members read memberships" on public.business_members for select using(user_id=(select auth.uid()) or private.is_business_member(business_id));
drop policy "members read credentials" on public.credentials;
create policy "members read credentials" on public.credentials for select using(private.is_business_member(business_id));
drop policy "members create credentials" on public.credentials;
create policy "members create credentials" on public.credentials for insert with check(private.is_business_member(business_id));
drop policy "members update pending credentials" on public.credentials;
create policy "members update pending credentials" on public.credentials for update using(private.is_business_member(business_id) and status in('pending','rejected'));
drop policy "public reads active kitchens" on public.kitchens;
create policy "public reads active kitchens" on public.kitchens for select using(active=true or private.is_business_member(owner_business_id));
drop policy "participants read bookings" on public.bookings;
create policy "participants read bookings" on public.bookings for select using(private.is_business_member(renter_business_id) or exists(select 1 from public.kitchens k where k.id=kitchen_id and private.is_business_member(k.owner_business_id)));
drop policy "renters create bookings" on public.bookings;
create policy "renters create bookings" on public.bookings for insert with check(created_by=(select auth.uid()) and private.is_business_member(renter_business_id));
drop policy "participants read booking resources" on public.booking_resources;
create policy "participants read booking resources" on public.booking_resources for select using(exists(select 1 from public.bookings b where b.id=booking_id and (private.is_business_member(b.renter_business_id) or exists(select 1 from public.kitchens k where k.id=b.kitchen_id and private.is_business_member(k.owner_business_id)))));
drop policy "members read client payments" on public.client_payments;
create policy "members read client payments" on public.client_payments for select using(private.is_business_member(business_id));
drop policy "members create client payments" on public.client_payments;
create policy "members create client payments" on public.client_payments for insert with check(private.is_business_member(business_id));
revoke execute on function public.is_business_member(uuid) from public, anon, authenticated;
